[package]
name = "cc-auth"
description = "Simple backend authorization system"
version = "0.1.1"
edition = "2021"
license = "MIT"
authors = ["Klimenty Titov <aclo.create@gmail.com>"]
repository = "https://github.com/markcda/cc-auth"

[dependencies]
bb8-redis = "0.15"
cc-utils = { version = "0.2", default-features = false, features = ["salvo", "bb8-redis"] }
chrono = { version = "0.4", features = ["serde"] }
passwords = "3.1"
serde = { version = "1.0", features = ["derive"] }
sha3 = "0.10"
serde_json = "1.0"
